/**
 * Placeholder content + shared types.
 *
 * Everything here is stand-in data so the UI is complete and browsable.
 * When the backend lands, replace POOL / PUBLISHED / SITE_STATS with real
 * queries — no component reads game data from anywhere else.
 */
import { STEAM_GAMES } from "./games.generated";

export type Game = {
  id: string;
  /** Steam appid, when the entry came from the store. */
  appid?: number;
  /** Steam header capsule URL. Falls back to a gradient when absent. */
  capsule?: string;
  name: string;
  genres: string[];
  price: string;
  score: string;
  reviews: string;
  /** e.g. "91%" — share of reviews that are positive. */
  positive: string;
  /** Genre / price / audience fit against the game you're swiping as. */
  fit: number;
  /** Why the Fit score is what it is, shown under the pills. */
  fitShared: string[];
  fitNotes: string[];
  releaseDate: string;
  platforms: string[];
  developer: string;
  publishers: string[];
  /**
   * Optional: real Steam entries have no public contact address, and the card
   * shows "unlocks on match" instead of inventing one.
   */
  contactEmail?: string;
  /** Steam feature/genre tags shown as pills. */
  tags: string[];
  description: string;
  steamUrl: string;
  /** Sheet flag: one of our own published titles — shows on /games. */
  ours?: boolean;
  /** Sheet flag: the single featured slot at the top of /games. */
  featured?: boolean;
};

export type GameStatus = "in_pool" | "in_review" | "refused";

export type MyGame = {
  id: string;
  name: string;
  genres: string[];
  price: string;
  score: string;
  reviews: string;
  positive: string;
  status: GameStatus;
  swipes: number;
  likes: number;
  matches: number;
};

export type PublishedGame = {
  name: string;
  studio: string;
  eyebrow: string;
  desc: string;
  tags: string[];
  cta: string;
  url: string;
  /** Steam header capsule. */
  capsule: string;
  /** Drives the eyebrow colour and the featured section's heading. */
  released: boolean;
};

/* -------------------------------------------------------------------------- */
/* Landing page numbers                                                        */
/* -------------------------------------------------------------------------- */

export const SITE_STATS = {
  gamesInPool: 173,
  studiosSwiping: 95,
  matchesMade: 61,
};

/** Pairs shown under the hero — real games so the covers are real. */
export const RECENT_MATCHES: [Game, Game][] = [
  [STEAM_GAMES[0], STEAM_GAMES[2]],
  [STEAM_GAMES[5], STEAM_GAMES[8]],
];

/* -------------------------------------------------------------------------- */
/* The swipe pool — games approved into the deck                               */
/* -------------------------------------------------------------------------- */

/**
 * The swipe pool. Real Steam entries generated by scripts/fetch-games.mjs —
 * re-run that script to refresh covers, prices and review scores.
 */
export const POOL: Game[] = STEAM_GAMES;

/** Shorter deck used for the "Try the deck" demo on the landing page. */
export const DEMO_DECK: Game[] = [POOL[9], POOL[2], POOL[4], POOL[6], POOL[1]];

/* -------------------------------------------------------------------------- */
/* Games we publish ourselves — the /games page                                */
/* -------------------------------------------------------------------------- */

export const PUBLISHED: {
  featured: PublishedGame;
  more: PublishedGame[];
} = {
  featured: {
    name: "Age of Clicks",
    studio: "David Ius",
    eyebrow: "New - Available now on Steam",
    released: true,
    desc: "A unique blend of **global strategy and clicker gameplay**. Manage your country with clicks: build factories, mine resources, and lead armies into battle. Click your enemies into surrender.",
    tags: ["Strategy", "Simulation", "Early Access"],
    cta: "Buy on Steam",
    url: "https://store.steampowered.com/app/4804480/Age_of_Clicks/",
    capsule:
      "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4804480/d9b08c2a4a5d0271b3b82af061d7a594ddce2d0f/header.jpg",
  },
  more: [
    {
      name: "Economic Miracle",
      studio: "Strudio Company",
      eyebrow: "Coming 2026",
      released: false,
      desc: "Take charge of any nation and lead it to greatness in the most ambitious geopolitical simulator of the modern era. Manage economy, laws, military, and diplomacy. Build the future without compromise.",
      tags: ["Strategy", "Simulation", "Multiplayer"],
      cta: "Wishlist on Steam",
      url: "https://store.steampowered.com/app/3738130/Economic_Miracle/",
      capsule:
        "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3738130/070adc7bdfc06d507ef9d6266c199f03caf375d3/header.jpg",
    },
    {
      name: "Money Garden Simulator",
      studio: "Sector Games",
      eyebrow: "Coming soon",
      released: false,
      desc: "Money literally grows on trees. Grow diverse currencies, expand your empire, and dominate the global economy - crush markets, manipulate exchange rates, and build the ultimate money garden.",
      tags: ["Simulation", "Indie", "Idle"],
      cta: "Wishlist on Steam",
      url: "https://store.steampowered.com/app/4202100/Money_Garden_Simulator/",
      capsule:
        "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4202100/ecaeb78671d6d37fe64f86f1e67599c92f84e32d/header.jpg",
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Dev Hub seed data                                                           */
/* -------------------------------------------------------------------------- */

export const SEED_MY_GAMES: MyGame[] = [
  {
    id: "mine-1",
    name: "Ant Farm Simulator",
    genres: ["Casual", "Indie", "Simulation", "Early Access"],
    price: "$0.99",
    score: "Mixed",
    reviews: "24",
    positive: "46%",
    status: "in_pool",
    swipes: 2,
    likes: 1,
    matches: 1,
  },
];


export const SEED_THREAD = [
  { from: "them" as const, body: "Hi :)", at: "2026-07-28 10:18:20" },
  { from: "them" as const, body: "Is 20% fine for you? I already created the bundle", at: "2026-07-28 10:22:08" },
  { from: "me" as const, body: "Hi", at: "2026-07-28 10:25:18" },
];

/* -------------------------------------------------------------------------- */
/* Catalog marquee — the games currently sitting in the swipe pool             */
/* -------------------------------------------------------------------------- */


/* -------------------------------------------------------------------------- */
/* "See how it works" video                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Set ONE of these. Leave both empty and the section shows a placeholder.
 *
 *  youtubeId — for a narrated walkthrough. Paste just the id from the URL:
 *              https://www.youtube.com/watch?v=dQw4w9WgXcQ  ->  "dQw4w9WgXcQ"
 *              Nothing loads from YouTube until the viewer clicks play.
 *
 *  src       — for a short, silent, looping screen capture you host yourself.
 *              Drop the file in /public and use "/how-it-works.mp4".
 *              Add `poster` (a still frame) so there's no black box on load.
 *
 * Google Drive is deliberately not supported — see README.
 */
export const HOW_IT_WORKS_VIDEO: {
  youtubeId?: string;
  src?: string;
  poster?: string;
} = {
  // youtubeId: "dQw4w9WgXcQ",
  // src: "/how-it-works.mp4",
  // poster: "/how-it-works.jpg",
};

/* -------------------------------------------------------------------------- */
/* FAQ — closes the landing page                                               */
/* -------------------------------------------------------------------------- */

export const FAQ: { q: string; a: string }[] = [
  {
    q: "What do I need to join the Dev Hub?",
    a: "A game on Steam and an email address — that's it. Paste your store link and we verify it, instantly if your account email matches the game's Steam contact, otherwise by a quick manual check. No portfolio, no application, no follower count.",
  },
  {
    q: "Is it really free? What's the catch?",
    a: "Free, forever. No revenue share, no bundle-slot commitment, no payment at any point. We don't take a cut of bundles you ship, and we never occupy a slot on your store page. Any match you make always needs your OK before anything happens.",
  },
  {
    q: "Who can see the games I swipe on?",
    a: "Nobody. Your likes and passes stay private until they're mutual — the other developer only learns you were interested if they liked your game too. There's no way to see who passed on you, by design.",
  },
  {
    q: "What actually happens when we match?",
    a: "You both get each other's studio profile and contact details straight away, plus a conversation in the hub so you don't have to hunt for emails. Every match also comes with a bundle kit: artwork in all six Steamworks formats, a store-description draft, and a suggested discount with the reasoning spelled out.",
  },
  {
    q: "Do I have to bundle with everyone I match with?",
    a: "No. A match just opens a conversation — it commits you to nothing. Plenty of matches turn into a chat that goes nowhere, and that's fine. Nothing reaches your Steam page without you setting it up yourself.",
  },
  {
    q: "How is the Fit score calculated?",
    a: "It scores how well a game would sell next to yours, based on genre overlap, price bracket and audience similarity. It's a suggestion for ordering the deck, not a verdict — plenty of good bundles are lower-scored pairings that just made sense to both studios.",
  },
  {
    q: "How long does approval take, and how many games can I add?",
    a: "Up to 5 business days if your game needs a manual review, and usually much faster. Instant if your email matches the game's Steam contact. You can add up to 25 games per account and swipe as any one of them.",
  },
  {
    q: "When's the right time to launch a bundle?",
    a: "The hub's launch-window planner suggests concrete two-week windows that dodge Next Fests and seasonal sales, so your bundle doesn't drown in Steam's own noise. Generally you want clear air either side of a big sale event, not the middle of one.",
  },
];

/* -------------------------------------------------------------------------- */
/* Placeholder cover art                                                       */
/* -------------------------------------------------------------------------- */

const ART_GRADIENTS: [string, string][] = [
  ["#3b1d5e", "#8b2fb8"], ["#0f3b52", "#1d8fa8"], ["#5e2c12", "#c47420"],
  ["#12402c", "#2f9e6b"], ["#3d1420", "#a83250"], ["#1a2340", "#3f5fa8"],
  ["#432c0e", "#96701c"], ["#2b1442", "#6b3fb0"], ["#0e3340", "#2a7d8c"],
  ["#401414", "#a33c2c"], ["#16341c", "#4d8f3a"], ["#2d1836", "#7c4a9e"],
];

function hashOf(str: string) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return h;
}

/**
 * Deterministic gradient stand-in for a Steam header capsule.
 * Real builds swap this for
 * `https://cdn.akamai.steamstatic.com/steam/apps/<appid>/header.jpg`.
 */
export function artGradient(name: string) {
  const [a, b] = ART_GRADIENTS[hashOf(name) % ART_GRADIENTS.length];
  return `linear-gradient(135deg, ${a}, ${b})`;
}
