/**
 * Real Steam data, generated by scripts/fetch-games.mjs.
 * Do not edit by hand — re-run the script to refresh.
 *
 * Fit scores are computed against a reference game
 * (Casual, Indie, Simulation @ $0.99), which stands in for "your game"
 * until real per-user scoring exists.
 */
import type { Game } from "./data";

export const STEAM_GAMES: Game[] = [
  {
    "id": "s413150",
    "appid": 413150,
    "name": "Stardew Valley",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg?t=1754692865",
    "genres": [
      "Indie",
      "RPG",
      "Simulation"
    ],
    "price": "$14.99",
    "score": "Overwhelmingly Positive",
    "reviews": "1.0M",
    "positive": "98%",
    "fit": 89,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "different price range",
      "similar audience"
    ],
    "releaseDate": "Feb 26, 2016",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "ConcernedApe",
    "publishers": [
      "ConcernedApe"
    ],
    "tags": [
      "Indie",
      "RPG",
      "Simulation",
      "Single-player",
      "Multi-player",
      "Co-op",
      "Online Co-op"
    ],
    "description": "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?",
    "steamUrl": "https://store.steampowered.com/app/413150/"
  },
  {
    "id": "s367520",
    "appid": 367520,
    "name": "Hollow Knight",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/367520/3c3489495136b26b34f8a9543c7f5645b99d388c/header.jpg?t=1776125684",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$14.99",
    "score": "Overwhelmingly Positive",
    "reviews": "554.1K",
    "positive": "97%",
    "fit": 78,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "different price range",
      "overlapping audience"
    ],
    "releaseDate": "Feb 24, 2017",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Team Cherry",
    "publishers": [
      "Team Cherry"
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud"
    ],
    "description": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style.",
    "steamUrl": "https://store.steampowered.com/app/367520/"
  },
  {
    "id": "s646570",
    "appid": 646570,
    "name": "Slay the Spire",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/646570/header.jpg?t=1774015376",
    "genres": [
      "Indie",
      "Strategy"
    ],
    "price": "$6.24",
    "score": "Overwhelmingly Positive",
    "reviews": "216.8K",
    "positive": "97%",
    "fit": 78,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "different price range",
      "overlapping audience"
    ],
    "releaseDate": "Jan 23, 2019",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Mega Crit",
    "publishers": [
      "Mega Crit"
    ],
    "tags": [
      "Indie",
      "Strategy",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Adjustable Text Size",
      "Custom Volume Controls"
    ],
    "description": "We fused card games and roguelikes together to make the best single player deckbuilder we could. Craft a unique deck, encounter bizarre creatures, discover relics of immense power, and Slay the Spire!",
    "steamUrl": "https://store.steampowered.com/app/646570/"
  },
  {
    "id": "s268910",
    "appid": 268910,
    "name": "Cuphead",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/268910/header.jpg?t=1709068852",
    "genres": [
      "Action",
      "Indie"
    ],
    "price": "$19.99",
    "score": "Overwhelmingly Positive",
    "reviews": "217.9K",
    "positive": "96%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Sep 29, 2017",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "Studio MDHR Entertainment Inc.",
    "publishers": [
      "Studio MDHR Entertainment Inc."
    ],
    "tags": [
      "Action",
      "Indie",
      "Single-player",
      "Multi-player",
      "Co-op",
      "Shared/Split Screen Co-op",
      "Shared/Split Screen"
    ],
    "description": "Cuphead is a classic run and gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, the visuals and audio are painstakingly created with the same techniques of the era, i.e. traditional hand drawn cel animation,",
    "steamUrl": "https://store.steampowered.com/app/268910/"
  },
  {
    "id": "s391540",
    "appid": 391540,
    "name": "Undertale",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/391540/header.jpg?t=1757349115",
    "genres": [
      "Indie",
      "RPG"
    ],
    "price": "$2.49",
    "score": "Overwhelmingly Positive",
    "reviews": "333.2K",
    "positive": "96%",
    "fit": 84,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "similar price range",
      "overlapping audience"
    ],
    "releaseDate": "Sep 15, 2015",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "tobyfox",
    "publishers": [
      "tobyfox"
    ],
    "tags": [
      "Indie",
      "RPG",
      "Single-player",
      "Family Sharing"
    ],
    "description": "UNDERTALE! The RPG game where you don't have to destroy anyone.",
    "steamUrl": "https://store.steampowered.com/app/391540/"
  },
  {
    "id": "s504230",
    "appid": 504230,
    "name": "Celeste",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/504230/header.jpg?t=1714089525",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$19.99",
    "score": "Overwhelmingly Positive",
    "reviews": "144.9K",
    "positive": "97%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Jan 25, 2018",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Maddy Makes Games Inc.",
    "publishers": [
      "Maddy Makes Games Inc."
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "DualShock Controller Support"
    ],
    "description": "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the ",
    "steamUrl": "https://store.steampowered.com/app/504230/"
  },
  {
    "id": "s588650",
    "appid": 588650,
    "name": "Dead Cells",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg?t=1779086887",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$12.49",
    "score": "Overwhelmingly Positive",
    "reviews": "182.1K",
    "positive": "97%",
    "fit": 78,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "different price range",
      "overlapping audience"
    ],
    "releaseDate": "Aug 6, 2018",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Motion Twin",
    "publishers": [
      "Motion Twin"
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud"
    ],
    "description": "Dead Cells is a roguelite, metroidvania inspired, action-platformer. You'll explore a sprawling, ever-changing castle... assuming you’re able to fight your way past its keepers in 2D souls-lite combat. No checkpoints. Kill, die, learn, repe",
    "steamUrl": "https://store.steampowered.com/app/588650/"
  },
  {
    "id": "s105600",
    "appid": 105600,
    "name": "Terraria",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg?t=1769844435",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$9.99",
    "score": "Overwhelmingly Positive",
    "reviews": "1.5M",
    "positive": "97%",
    "fit": 78,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "different price range",
      "overlapping audience"
    ],
    "releaseDate": "May 16, 2011",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Re-Logic",
    "publishers": [
      "Re-Logic"
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "RPG",
      "Single-player",
      "Multi-player",
      "PvP"
    ],
    "description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!",
    "steamUrl": "https://store.steampowered.com/app/105600/"
  },
  {
    "id": "s250900",
    "appid": 250900,
    "name": "The Binding of Isaac: Rebirth",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/250900/header.jpg?t=1731977365",
    "genres": [
      "Action"
    ],
    "price": "$14.99",
    "score": "Overwhelmingly Positive",
    "reviews": "435.8K",
    "positive": "97%",
    "fit": 67,
    "fitShared": [
      "Action"
    ],
    "fitNotes": [
      "different price range",
      "overlapping audience"
    ],
    "releaseDate": "Nov 4, 2014",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Nicalis, Inc.",
    "publishers": [
      "Nicalis, Inc."
    ],
    "tags": [
      "Action",
      "Single-player",
      "Multi-player",
      "Shared/Split Screen",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud"
    ],
    "description": "The Binding of Isaac: Rebirth is a randomly generated action RPG shooter with heavy Rogue-like elements. Following Isaac on his journey players will find bizarre treasures that change Isaac’s form giving him super human abilities and enabli",
    "steamUrl": "https://store.steampowered.com/app/250900/"
  },
  {
    "id": "s294100",
    "appid": 294100,
    "name": "RimWorld",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/294100/76e0613b8197327299d5dbabb0a7fd7828a689a2/header.jpg?t=1782756789",
    "genres": [
      "Indie",
      "Simulation",
      "Strategy"
    ],
    "price": "$34.99",
    "score": "Overwhelmingly Positive",
    "reviews": "243.7K",
    "positive": "98%",
    "fit": 83,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "much higher price range",
      "similar audience"
    ],
    "releaseDate": "Oct 17, 2018",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Ludeon Studios",
    "publishers": [
      "Ludeon Studios"
    ],
    "tags": [
      "Indie",
      "Simulation",
      "Strategy",
      "Single-player",
      "Adjustable Text Size",
      "Camera Comfort",
      "Custom Volume Controls"
    ],
    "description": "A sci-fi colony sim driven by an intelligent AI storyteller. Generates stories by simulating psychology, ecology, gunplay, melee combat, climate, biomes, diplomacy, interpersonal relationships, art, medicine, trade, and more.",
    "steamUrl": "https://store.steampowered.com/app/294100/"
  },
  {
    "id": "s1145360",
    "appid": 1145360,
    "name": "Hades",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg?t=1758127023",
    "genres": [
      "Action",
      "Indie",
      "RPG"
    ],
    "price": "$24.99",
    "score": "Overwhelmingly Positive",
    "reviews": "306.9K",
    "positive": "98%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Sep 17, 2020",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "Supergiant Games",
    "publishers": [
      "Supergiant Games"
    ],
    "tags": [
      "Action",
      "Indie",
      "RPG",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Captions available"
    ],
    "description": "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.",
    "steamUrl": "https://store.steampowered.com/app/1145360/"
  },
  {
    "id": "s632360",
    "appid": 632360,
    "name": "Risk of Rain 2",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/632360/header.jpg?t=1783621122",
    "genres": [
      "Action",
      "Indie"
    ],
    "price": "$24.99",
    "score": "Very Positive",
    "reviews": "350.8K",
    "positive": "94%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Aug 11, 2020",
    "platforms": [
      "Windows"
    ],
    "developer": "Hopoo Games",
    "publishers": [
      "Gearbox Publishing",
      "2K"
    ],
    "tags": [
      "Action",
      "Indie",
      "Single-player",
      "Multi-player",
      "PvP",
      "Online PvP",
      "Co-op"
    ],
    "description": "Escape a chaotic alien planet by fighting through hordes of frenzied monsters – with your friends, or on your own. Combine loot in surprising ways and master each character until you become the havoc you feared upon your first crash landing",
    "steamUrl": "https://store.steampowered.com/app/632360/"
  },
  {
    "id": "s262060",
    "appid": 262060,
    "name": "Darkest Dungeon®",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/262060/header.jpg?t=1769780578",
    "genres": [
      "Indie",
      "RPG",
      "Strategy"
    ],
    "price": "$24.99",
    "score": "Very Positive",
    "reviews": "160.9K",
    "positive": "92%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Jan 19, 2016",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Red Hook Studios",
    "publishers": [
      "Red Hook Studios"
    ],
    "tags": [
      "Indie",
      "RPG",
      "Strategy",
      "Single-player",
      "Steam Achievements",
      "DualShock Controller Support",
      "Partial Controller Support"
    ],
    "description": "Darkest Dungeon is a challenging gothic roguelike turn-based RPG about the psychological stresses of adventuring. Recruit, train, and lead a team of flawed heroes against unimaginable horrors, stress, disease, and the ever-encroaching dark.",
    "steamUrl": "https://store.steampowered.com/app/262060/"
  },
  {
    "id": "s322330",
    "appid": 322330,
    "name": "Don't Starve Together",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/322330/da5d1bc20a2b35fe987c68047ba96a7f3d25c982/header_alt_assets_50.jpg?t=1782413299",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$14.99",
    "score": "Very Positive",
    "reviews": "540.1K",
    "positive": "95%",
    "fit": 89,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "different price range",
      "similar audience"
    ],
    "releaseDate": "Apr 21, 2016",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Klei Entertainment",
    "publishers": [
      "Klei Entertainment"
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "RPG",
      "Simulation",
      "Strategy",
      "Single-player"
    ],
    "description": "Fight, Farm, Build and Explore Together in the standalone multiplayer expansion to the uncompromising wilderness survival game, Don't Starve.",
    "steamUrl": "https://store.steampowered.com/app/322330/"
  },
  {
    "id": "s1794680",
    "appid": 1794680,
    "name": "Vampire Survivors",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1794680/2ca07b690dde645771125ed9d9206c4c5fde4dd4/header.jpg?t=1781096909",
    "genres": [
      "Action",
      "Casual",
      "Indie"
    ],
    "price": "$3.99",
    "score": "Overwhelmingly Positive",
    "reviews": "264.3K",
    "positive": "98%",
    "fit": 95,
    "fitShared": [
      "Casual",
      "Indie"
    ],
    "fitNotes": [
      "similar price range",
      "similar audience"
    ],
    "releaseDate": "Oct 20, 2022",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "poncle",
    "publishers": [
      "poncle"
    ],
    "tags": [
      "Action",
      "Casual",
      "Indie",
      "RPG",
      "Single-player",
      "Multi-player",
      "Co-op"
    ],
    "description": "Mow down thousands of night creatures and survive until dawn! Vampire Survivors is a gothic horror casual game with rogue-lite elements, where your choices can allow you to quickly snowball against the hundreds of monsters that get thrown a",
    "steamUrl": "https://store.steampowered.com/app/1794680/"
  },
  {
    "id": "s233860",
    "appid": 233860,
    "name": "Kenshi",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/233860/fa72ac8a032fd876780cd5b554e4c03b4976ef74/header.jpg?t=1779293333",
    "genres": [
      "Action",
      "Indie",
      "RPG"
    ],
    "price": "$29.99",
    "score": "Overwhelmingly Positive",
    "reviews": "115.0K",
    "positive": "96%",
    "fit": 83,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "much higher price range",
      "similar audience"
    ],
    "releaseDate": "Dec 6, 2018",
    "platforms": [
      "Windows"
    ],
    "developer": "Lo-Fi Games",
    "publishers": [
      "Lo-Fi Games"
    ],
    "tags": [
      "Action",
      "Indie",
      "RPG",
      "Simulation",
      "Strategy",
      "Single-player",
      "Includes level editor"
    ],
    "description": "A free-roaming squad based RPG. Focusing on open-ended sandbox gameplay features rather than a linear story. Be a trader, a thief, a rebel, a warlord, an adventurer, a farmer, a slave, or just food for the cannibals. Train your men up from ",
    "steamUrl": "https://store.steampowered.com/app/233860/"
  },
  {
    "id": "s1057090",
    "appid": 1057090,
    "name": "Ori and the Will of the Wisps",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1057090/header.jpg?t=1759530749",
    "genres": [
      "Action"
    ],
    "price": "$29.99",
    "score": "Overwhelmingly Positive",
    "reviews": "145.7K",
    "positive": "97%",
    "fit": 61,
    "fitShared": [
      "Action"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Mar 10, 2020",
    "platforms": [
      "Windows"
    ],
    "developer": "Moon Studios GmbH",
    "publishers": [
      "Xbox Game Studios"
    ],
    "tags": [
      "Action",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud",
      "HDR available",
      "Family Sharing"
    ],
    "description": "Play the critically acclaimed masterpiece. Embark on a new journey in a vast, exotic world where you’ll encounter towering enemies and challenging puzzles on your quest to unravel Ori’s destiny.",
    "steamUrl": "https://store.steampowered.com/app/1057090/"
  },
  {
    "id": "s387290",
    "appid": 387290,
    "name": "Ori and the Blind Forest: Definitive Edition",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/387290/header.jpg?t=1701967651",
    "genres": [
      "Action"
    ],
    "price": "$19.99",
    "score": "Overwhelmingly Positive",
    "reviews": "71.2K",
    "positive": "95%",
    "fit": 61,
    "fitShared": [
      "Action"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Apr 27, 2016",
    "platforms": [
      "Windows"
    ],
    "developer": "Moon Studios GmbH",
    "publishers": [
      "Xbox Game Studios"
    ],
    "tags": [
      "Action",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud",
      "Stats",
      "Family Sharing"
    ],
    "description": "“Ori and the Blind Forest” tells the tale of a young orphan destined for heroics, through a visually stunning Action-Platformer crafted by Moon Studios.",
    "steamUrl": "https://store.steampowered.com/app/387290/"
  },
  {
    "id": "s2379780",
    "appid": 2379780,
    "name": "Balatro",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2379780/7a85430784e4d613cdb0547414d8cf16ffa45747/header.jpg?t=1781540048",
    "genres": [
      "Casual",
      "Indie",
      "Strategy"
    ],
    "price": "$14.99",
    "score": "Overwhelmingly Positive",
    "reviews": "195.8K",
    "positive": "98%",
    "fit": 89,
    "fitShared": [
      "Casual",
      "Indie"
    ],
    "fitNotes": [
      "different price range",
      "similar audience"
    ],
    "releaseDate": "Feb 20, 2024",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "LocalThunk",
    "publishers": [
      "Playstack"
    ],
    "tags": [
      "Casual",
      "Indie",
      "Strategy",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Color Alternatives"
    ],
    "description": "The poker roguelike. Balatro is a hypnotically satisfying deckbuilder where you play illegal poker hands, discover game-changing jokers, and trigger adrenaline-pumping, outrageous combos.",
    "steamUrl": "https://store.steampowered.com/app/2379780/"
  },
  {
    "id": "s1868140",
    "appid": 1868140,
    "name": "DAVE THE DIVER",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1868140/81bdb3bce15d27ca1b4554a642d91096e89be229/header.jpg?t=1784533018",
    "genres": [
      "Adventure",
      "Casual",
      "RPG"
    ],
    "price": "$19.99",
    "score": "Overwhelmingly Positive",
    "reviews": "159.4K",
    "positive": "97%",
    "fit": 83,
    "fitShared": [
      "Casual",
      "Simulation"
    ],
    "fitNotes": [
      "much higher price range",
      "similar audience"
    ],
    "releaseDate": "Jun 28, 2023",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "MINTROCKET",
    "publishers": [
      "MINTROCKET"
    ],
    "tags": [
      "Adventure",
      "Casual",
      "RPG",
      "Simulation",
      "Single-player",
      "Steam Achievements",
      "Full controller support"
    ],
    "description": "DAVE THE DIVER is a casual, singleplayer adventure RPG featuring deep-sea exploration and fishing during the day and sushi restaurant management at night. Join Dave and his quirky friends as they seek to uncover the secrets of the mysteriou",
    "steamUrl": "https://store.steampowered.com/app/1868140/"
  },
  {
    "id": "s1332010",
    "appid": 1332010,
    "name": "Stray",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1332010/71daca1910d664d31240b9623a495e0c0828807f/header.jpg?t=1779927784",
    "genres": [
      "Adventure",
      "Indie"
    ],
    "price": "$29.99",
    "score": "Overwhelmingly Positive",
    "reviews": "176.2K",
    "positive": "97%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Jul 19, 2022",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "BlueTwelve Studio",
    "publishers": [
      "Annapurna Interactive"
    ],
    "tags": [
      "Adventure",
      "Indie",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud",
      "Family Sharing"
    ],
    "description": "Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten cybercity and find their way home.",
    "steamUrl": "https://store.steampowered.com/app/1332010/"
  },
  {
    "id": "s1966720",
    "appid": 1966720,
    "name": "Lethal Company",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1966720/header.jpg?t=1775380053",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$9.99",
    "score": "Overwhelmingly Positive",
    "reviews": "509.9K",
    "positive": "97%",
    "fit": 78,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "different price range",
      "overlapping audience"
    ],
    "releaseDate": "Oct 23, 2023",
    "platforms": [
      "Windows"
    ],
    "developer": "Zeekerss",
    "publishers": [
      "Zeekerss"
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "Early Access",
      "Single-player",
      "Multi-player",
      "Co-op"
    ],
    "description": "A co-op horror about scavenging at abandoned moons to sell scrap to the Company.",
    "steamUrl": "https://store.steampowered.com/app/1966720/"
  },
  {
    "id": "s448510",
    "appid": 448510,
    "name": "Overcooked",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/448510/header.jpg?t=1780480467",
    "genres": [
      "Action",
      "Casual",
      "Indie"
    ],
    "price": "$4.09",
    "score": "Very Positive",
    "reviews": "16.6K",
    "positive": "90%",
    "fit": 97,
    "fitShared": [
      "Casual",
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "similar price range",
      "similar audience"
    ],
    "releaseDate": "Aug 3, 2016",
    "platforms": [
      "Windows"
    ],
    "developer": "Ghost Town Games Ltd.",
    "publishers": [
      "Team17 Digital Ltd"
    ],
    "tags": [
      "Action",
      "Casual",
      "Indie",
      "Simulation",
      "Single-player",
      "Multi-player",
      "PvP"
    ],
    "description": "Overcooked is a chaotic couch co-op cooking game for one to four players. Working as a team, you and your fellow chefs must prepare, cook and serve up a variety of tasty orders before the baying customers storm out in a huff.",
    "steamUrl": "https://store.steampowered.com/app/448510/"
  },
  {
    "id": "s1229490",
    "appid": 1229490,
    "name": "ULTRAKILL",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1229490/header.jpg?t=1783942574",
    "genres": [
      "Action",
      "Indie",
      "Early Access"
    ],
    "price": "$29.99",
    "score": "Overwhelmingly Positive",
    "reviews": "238.5K",
    "positive": "97%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Sep 3, 2020",
    "platforms": [
      "Windows"
    ],
    "developer": "Arsi \"Hakita\" Patala",
    "publishers": [
      "New Blood Interactive"
    ],
    "tags": [
      "Action",
      "Indie",
      "Early Access",
      "Single-player",
      "Full controller support",
      "DualShock Controller Support",
      "DualSense Controller Support"
    ],
    "description": "ULTRAKILL is a fast-paced ultra-violent retro FPS that combines the skill-based style scoring of character action games with the unadulterated carnage inspired by the best shooters of the '90s. Rip apart your foes with varied destructive we",
    "steamUrl": "https://store.steampowered.com/app/1229490/"
  },
  {
    "id": "s244850",
    "appid": 244850,
    "name": "Space Engineers",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/244850/3658a69c81af5f4014b0ffa88941285e74825b86/header.jpg?t=1785173739",
    "genres": [
      "Action",
      "Indie",
      "Simulation"
    ],
    "price": "$9.99",
    "score": "Very Positive",
    "reviews": "134.1K",
    "positive": "89%",
    "fit": 85,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "different price range",
      "similar audience"
    ],
    "releaseDate": "Feb 28, 2019",
    "platforms": [
      "Windows"
    ],
    "developer": "Keen Software House",
    "publishers": [
      "Keen Software House"
    ],
    "tags": [
      "Action",
      "Indie",
      "Simulation",
      "Strategy",
      "Single-player",
      "Multi-player",
      "PvP"
    ],
    "description": "Space Engineers is a sandbox engineering game where you design and build ships, stations, and planetary bases in a fully destructible environment. Explore planets and space, mine resources, survive hazards, and engage in combat alone or wit",
    "steamUrl": "https://store.steampowered.com/app/244850/"
  },
  {
    "id": "s219740",
    "appid": 219740,
    "name": "Don't Starve",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/219740/88641e235d75934ea9f7ed4e947edfd9da682732/header.jpg?t=1781206408",
    "genres": [
      "Adventure",
      "Indie",
      "Simulation"
    ],
    "price": "$9.99",
    "score": "Overwhelmingly Positive",
    "reviews": "113.3K",
    "positive": "97%",
    "fit": 89,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "different price range",
      "similar audience"
    ],
    "releaseDate": "Apr 23, 2013",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Klei Entertainment",
    "publishers": [
      "Klei Entertainment"
    ],
    "tags": [
      "Adventure",
      "Indie",
      "Simulation",
      "Single-player",
      "Full controller support",
      "Steam Cloud",
      "Family Sharing"
    ],
    "description": "Don’t Starve is an uncompromising wilderness survival game full of science and magic. Enter a strange and unexplored world full of strange creatures, dangers, and surprises. Gather resources to craft items and structures that match your sur",
    "steamUrl": "https://store.steampowered.com/app/219740/"
  },
  {
    "id": "s427520",
    "appid": 427520,
    "name": "Factorio",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/427520/header.jpg?t=1763986204",
    "genres": [
      "Casual",
      "Indie",
      "Simulation"
    ],
    "price": "$35.00",
    "score": "Overwhelmingly Positive",
    "reviews": "232.5K",
    "positive": "98%",
    "fit": 94,
    "fitShared": [
      "Casual",
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "much higher price range",
      "similar audience"
    ],
    "releaseDate": "Aug 14, 2020",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "Wube Software LTD.",
    "publishers": [
      "Wube Software LTD."
    ],
    "tags": [
      "Casual",
      "Indie",
      "Simulation",
      "Strategy",
      "Single-player",
      "Multi-player",
      "Co-op"
    ],
    "description": "Factorio is a game about building and creating automated factories to produce items of increasing complexity, within an infinite 2D world. Use your imagination to design your factory, combine simple elements into ingenious structures, and f",
    "steamUrl": "https://store.steampowered.com/app/427520/"
  },
  {
    "id": "s774361",
    "appid": 774361,
    "name": "Blasphemous",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/774361/header.jpg?t=1780479368",
    "genres": [
      "Action",
      "Adventure",
      "Indie"
    ],
    "price": "$24.99",
    "score": "Very Positive",
    "reviews": "66.1K",
    "positive": "90%",
    "fit": 72,
    "fitShared": [
      "Indie"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Sep 10, 2019",
    "platforms": [
      "Windows",
      "macOS",
      "Linux"
    ],
    "developer": "The Game Kitchen",
    "publishers": [
      "Team17"
    ],
    "tags": [
      "Action",
      "Adventure",
      "Indie",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Steam Cloud"
    ],
    "description": "Blasphemous is a brutal action-platformer with skilled hack’n slash combat set in the nightmare world of Cvstodia. Explore, upgrade your abilities, and perform savage executions on the hordes of enemies that stand between you and your quest",
    "steamUrl": "https://store.steampowered.com/app/774361/"
  },
  {
    "id": "s1091500",
    "appid": 1091500,
    "name": "Cyberpunk 2077",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/e9047d8ec47ae3d94bb8b464fb0fc9e9972b4ac7/header.jpg?t=1784714077",
    "genres": [
      "RPG"
    ],
    "price": "$17.99",
    "score": "Very Positive",
    "reviews": "963.8K",
    "positive": "87%",
    "fit": 57,
    "fitShared": [
      "RPG"
    ],
    "fitNotes": [
      "much higher price range",
      "overlapping audience"
    ],
    "releaseDate": "Dec 9, 2020",
    "platforms": [
      "Windows",
      "macOS"
    ],
    "developer": "CD PROJEKT RED",
    "publishers": [
      "CD PROJEKT RED"
    ],
    "tags": [
      "RPG",
      "Single-player",
      "Steam Achievements",
      "Full controller support",
      "Adjustable Text Size",
      "Camera Comfort",
      "Color Alternatives"
    ],
    "description": "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.",
    "steamUrl": "https://store.steampowered.com/app/1091500/"
  },
  {
    "id": "s975370",
    "appid": 975370,
    "name": "Dwarf Fortress",
    "capsule": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/975370/34e18f5695fffd64458b78110930abc5258ccd14/header.jpg?t=1779740424",
    "genres": [
      "Indie",
      "Simulation",
      "Strategy"
    ],
    "price": "$29.99",
    "score": "Very Positive",
    "reviews": "31.3K",
    "positive": "95%",
    "fit": 83,
    "fitShared": [
      "Indie",
      "Simulation"
    ],
    "fitNotes": [
      "much higher price range",
      "similar audience"
    ],
    "releaseDate": "Dec 6, 2022",
    "platforms": [
      "Windows",
      "Linux"
    ],
    "developer": "Bay 12 Games",
    "publishers": [
      "Kitfox Games"
    ],
    "tags": [
      "Indie",
      "Simulation",
      "Strategy",
      "Single-player",
      "Family Sharing"
    ],
    "description": "Build a fortress and try to help your dwarves survive against a deeply generated world. Keep your dwarves happy, grow their community and beware of digging too deeply. The deepest, most intricate simulation of a world that's ever been creat",
    "steamUrl": "https://store.steampowered.com/app/975370/"
  }
];
